language: node_js
node_js:
  - "4.2"
  - "4.1"
  - "4.0"
before_install:
  - openssl aes-256-cbc -K $encrypted_4bdc43d0e784_key -iv $encrypted_4bdc43d0e784_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
before_script:
  - npm install -g gulp
script: gulp
# Send coverage data to Coveralls
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
